import Layout from '../components/layout'
import styles from '../styles/Home.module.css'
import { GetStaticProps, GetStaticPropsContext, InferGetStaticPropsType, NextPage } from 'next' // TypeScript の型データ

type Props = InferGetStaticPropsType<typeof getStaticProps>
type Result = {
    id: number,
    name: string
}

// getStaticProps は、実装者が大きな変更をしない限り Promise を返却する = 条件は必ず真に流れる
// ★★TODO: エラー消す (参考：https://zenn.dev/eitches/articles/2021-0424-getstaticprops-type)
export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext<{ slug: string }>) => {

    const names = ['takunagai', 'GeoSot']
    let jobs = []
    let div: HTMLParagraphElement

    // const post = getPost(context.params.slug)

    for (let name of names) {
        let job = fetch(`https://api.github.com/users/${name}`).then(
            successResponse => {
                if (successResponse.status != 200) {
                    return null
                } else {
                    return successResponse.json()
                }
            },
            failResponse => {
                return null
            }
        )
        jobs.push(job) // Array of Users json Data
    }
    let results = await Promise.all(jobs)

    return {
        props: {
            results,
        },
    }
}

const Home: NextPage<Props> = ({ results }) => {
    return (
        <Layout
            home
            title="ナガイ商店.com - 兵庫県川西市 Web 制作"
            description="概要です。"
        >
            <h1 className="text-3xl font-bold underline">見出し１です。</h1>
            <p className={styles.primary}>内容</p>
            <ul>
                {results.map((result: Result, index: number) => (
                    <li key={index}>{result.id} {result.name}</li>
                ))}
            </ul>
        </Layout>
    )
}

export default Home



// 元のもの
// import Head from 'nextjs-website/head'
// import Image from 'nextjs-website/image'
// import Link from 'nextjs-website/link'
// import styles from '../styles/Home.module.css'
//
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create nextjs-website app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//
//       <nav>
//           <ul>
//               <li><Link href="/">Home</Link></li>
//               <li><Link href="/about">About</Link></li>
//           </ul>
//       </nav>
//
//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>
//
//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>
//
//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>
//
//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>
//
//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//
//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
